### PR TITLE
Added the possibility of defining data attributes on actions

### PR DESCRIPTION
**Pull request by dominiclord**
Example

```
...
"actions": [
    {
        "ident": "view_en",
        "label": {
            "en": "View",
            "fr": "Voir"
        },
        "target": "_blank",
        "dataAttributes": [
            {
                "key": "lang",
                "value": "en"
            }
        ],
        "condition": "{{ isEn }}",
        "url": "{{# withBaseUrl }}{{ url.en }}{{/ withBaseUrl }}"
    },
    {
        "ident": "view_fr",
        "label": {
            "en": "View",
            "fr": "Voir"
        },
        "cssClasses": "hidden",
        "target": "_blank",
        "dataAttributes": [
            {
                "key": "lang",
                "value": "fr"
            }
        ],
        "condition": "{{ isFr }}",
        "url": "{{# withBaseUrl }}{{ url.fr }}{{/ withBaseUrl }}"
    },
...
```

### CODE REVIEW

**Comment by mcaskill** [comment]
I would add:
```
if ($menuItem['data_attributes']) {
	$menuItem['data_attributes'] = $menuItem['data_attributes'];
}
```
Cause snake-case is part of our lives.

**Comment by mcaskill** [comment]
We should also consider adding a function or method to stringify an associative array to HTML attributes. Like in [mcaskill/charcoal-support](https://github.com/mcaskill/charcoal-support/blob/0.8.7/src/View/HtmlableTrait.php) for the `TableWidget`.

**Comment by dominiclord** [comment]
I agree about snake casing, but ActionContainerTrait already makes use of camel case in a few places, so I followed suit.

`buttonType` `actionType` `cssClasses`.

**Comment by mcaskill** [comment]
True. I wonder if it shouldn't have just been all camelCase everywhere.

**Pull request merged**
